---
dependency:
  name: galaxy
driver:
  name: podman
platforms:
  - name: rocky-9
    image: rockylinux:9
    pre_build_image: true

  - name: debian-11
    image: debian:bullseye
    dockerfile: ../../../../testing/container_files/Dockerfile.j2
    pre_build_image: false

  - name: ubuntu-22
    image: ubuntu:22.04
    dockerfile: ../../../../testing/container_files/Dockerfile.j2
    pre_build_image: false

provisioner:
  name: ansible
verifier:
  name: ansible
