---
dependency:
  name: galaxy
driver:
  name: podman
platforms:
  - name: rocky-9
    image: rockylinux:9
    pre_build_image: true

  - name: debian-11
    image: debian:bullseye
    pre_build_image: false

  - name: ubuntu-22
    image: ubuntu:22.04
    pre_build_image: false

provisioner:
  name: ansible
  inventory:
    host_vars:
      rocky-9:
        package_install_packages:
          - sudo
          - python3
          - python3-pip
          - freeipa-client

        package_install_repositories:
          - name: epel
            url: https://dl.fedoraproject.org/pub/epel/9/Everything/x86_64/
            description: "EPEL Repo"
            dnf_dependencies:
              - crb
              - appstream  # Example, don't take for reference
          - dnf_dependencies:
              - resilientstorage
              - highavailability

      debian-11:
        package_install_packages:
          - sudo
          - python3
          - python3-pip
          - locales-all
          - freeipa-client

        package_install_repositories:
            - repo: "deb http://deb.debian.org/debian bullseye-backports main contrib non-free"
            - repo: "deb-src http://deb.debian.org/debian bullseye-backports main contrib non-free"

      ubuntu-22:
        package_install_packages:
          - sudo
          - python3
          - python3-pip
          - locales-all
          - freeipa-client
verifier:
  name: ansible
