---
- name: Verify
  hosts: all
  tasks:
    - name: Gather the package facts
      ansible.builtin.package_facts:
        manager: auto

    - name: Assert that packages are present
      vars:
        packages:
          debian-11:
            - sudo
            - python3
            - python3-pip
            - locales-all
            - vim
          ubuntu-22:
            - sudo
            - python3
            - python3-pip
            - vim
          rocky-9:
            - python3
            - python3-pip
            - vim-enhanced
      loop: "{{ packages[(ansible_distribution | lower + '-' + ansible_distribution_major_version | lower)] }}"
      ansible.builtin.assert:
        that: "item in ansible_facts.packages"
