---
- name: Gather variables per SO
  ansible.builtin.include_vars:
    file: "{{ role_path }}/vars/{{ ansible_os_family | lower }}.yml"

- name: Perform CAs installation
  ansible.builtin.include_tasks:
    file: install_cas.yml
