---
log: true

provisioner:
  name: ansible
  log: true
  inventory:
    host_vars:
      rocky-9:
        pbi_pknst_packages:
          - sudo
          - python3
          - python3-pip
          - vim

        pbi_pknst_repositories:
          - name: epel
            url: https://dl.fedoraproject.org/pub/epel/9/Everything/x86_64/
            description: "EPEL Repo"
            dnf_dependencies:
              - crb
              - appstream  # Example, don't take for reference
          - dnf_dependencies:
              - resilientstorage
              - highavailability

      debian-11:
        pbi_pknst_packages:
          - sudo
          - python3
          - python3-pip
          - locales-all
          - vim

        pbi_pknst_repositories:
            - repo: "deb http://deb.debian.org/debian bullseye-backports main contrib non-free"
            - repo: "deb-src http://deb.debian.org/debian bullseye-backports main contrib non-free"

      ubuntu-22:
        pbi_pknst_packages:
          - sudo
          - python3
          - python3-pip
          - locales-all
          - vim
