---
- name: Ensure the packer binary is present
  ansible.builtin.include_tasks:
    file: check_install_binary.yml

- name: Create the logs directory
  ansible.builtin.file:
    path: "{{ (ansible_user_dir, 'logs') | path_join }}"
    state: directory
    mode: "0755"

- name: Prepare workspace and run packer
  vars:
    _pbi_packer_base_run_dir: >-
      {{
        pbi_packer_workspace | default(pbi_packer_template_path | dirname)
      }}
    _pbi_packer_template_file_abs: >-
      {{
        (
          (pbi_packer_template_path is abs) |
          ternary(
            pbi_packer_template_path,
            [
              _pbi_packer_base_run_dir,
              pbi_packer_template_path
            ] | path_join | regex_replace('.j2$', '')
          )
        )
      }}
  block:
    - name: Prepare the needed files and variables
      ansible.builtin.include_tasks:
        file: prepare_workspace.yml

    - name: Run packer commands
      ansible.builtin.import_tasks:
        file: packer_run.yml
  always:
    - name: Delete the generated vars file
      when:
        - _pbi_packer_vars_file is defined
        - not pbi_packer_preserve_vars_file
      ansible.builtin.file:
        path: "{{ _pbi_packer_vars_file }}"
        state: absent
