---
- name: Fetch management connection
  vars:
    mngt_connections: >-
      {{
        pbi_network_connections |
        dict2items |
        selectattr('value.is_mngt_connection', 'defined') |
        selectattr(
            'value.is_mngt_connection',
            'equalto',
            true
        )
      }}
  ansible.builtin.set_fact:
    pbi_nstp_mngt_connection: >-
      {{
        mngt_connections if pbi_network_connections | length == 1 else ""
      }}
    cacheable: true

- name: Get SSH connection target IP
  when: pbi_nstp_mngt_connection == '' and 'SSH_CONNECTION' in ansible_env
  ansible.builtin.set_fact:
    pbi_nstp_ssh_target_connection: >-
      {{
        ((ansible_env.SSH_CONNECTION | split(' '))[2]) |
        pablintino.base_infra.nstp_filter_ip2cconn(pbi_network_connections)
      }}

- name: Set management connection if infered
  when: pbi_nstp_mngt_connection != ''
  ansible.builtin.set_fact:
    pbi_network_connections: >-
      {{
          pbi_network_connections |
          combine(
          {
            pbi_nstp_ssh_target_connection: {
              'is_mngt_connection': true
            }
          }
          , recursive=True)
      }}
    cacheable: true
