---
# Important: We only take into consideration the interfaces
# and connections we manage. Connections outside of the scope
# of the role are not part of the apply output and won't be
# considered
- name: Get SSH connection target IP
  when:
    - "'SSH_CONNECTION' in ansible_env"
    - >-
      (pbi_nstp_mngt_connection is not defined) or
      (pbi_nstp_mngt_interface is not defined)
  ansible.builtin.set_fact:
    _pbi_nstp_mngt_connection_data: >-
      {{
        _pbi_nstp_nmcli_apply_result |
        pablintino.base_infra.nstp_filter_applyres2conns |
        pablintino.base_infra.nstp_filter_ip2conn(
          ((ansible_env.SSH_CONNECTION | split(' '))[2])
        )
      }}

- name: Set management connection if infered
  when: >-
    _pbi_nstp_mngt_connection_data |
    default({}) |
    length > 0
  ansible.builtin.set_fact:
    pbi_nstp_mngt_connection: >-
      {{
        _pbi_nstp_mngt_connection_data['general.name']
      }}
    pbi_nstp_mngt_interface: >-
      {{
        _pbi_nstp_mngt_connection_data['general.ip-iface']
      }}
    cacheable: true
