---
- name: Set hostname
  ansible.builtin.hostname:
    name: "{{ network_setup_hostname }}"

- name: Add hostname to /etc/hosts
  vars:
    comment: ""
  lineinfile:
    dest: /etc/hosts
    regexp: "127[.]0[.]0[.]1.*"
    line: "127.0.0.1 localhost.localdomain localhost {{ network_setup_hostname }} # Ansible base_infra managed"
    state: present
  loop:
    
