---
- name: Gather roles variables per SO
  ansible.builtin.include_vars:
    file: "{{ role_path }}/vars/{{ ansible_os_family | lower }}_vars.yml"

- name: Install network related packages
  vars:
    pbi_pknst_packages_install_list: "{{ pbi_nstp_packages }}"
  ansible.builtin.include_role:
    name: package_install
    tasks_from: install_packages.yml

- name: Setup network-manager to handle all connections
  ansible.builtin.import_tasks:
    file: setup_network_manager.yml

- name: Configure connections
  ansible.builtin.import_tasks:
    file: setup_network_manager_connections.yml

- name: Set management connection properties
  ansible.builtin.import_tasks:
    file: detect_managment_connection.yml

- name: Ensure infra folder exists
  ansible.builtin.file:
    path: "{{ ansible_user_dir }}/.infra"
    state: directory

- name: Copy role related vars to the infra directory
  vars:
    pbi_nstp_role_file_content:
      pbi_nstp_connections: "{{ pbi_nstp_connections }}"
  ansible.builtin.copy:
    content: >-
      {{
        {
          'pbi_network_connections': pbi_nstp_role_file_content
        } | to_nice_yaml
      }}
    dest: "{{ pbi_nstp_networking_output_file_path }}"
