---
- name: Gather roles variables per SO
  ansible.builtin.include_vars:
    file: "{{ role_path }}/vars/{{ ansible_os_family | lower }}_vars.yml"

- name: Install network related packages
  vars:
    package_install_packages_list: "{{ network_setup_packages }}"
  ansible.builtin.import_role:
    name: package_install
    tasks_from: cache_update_install_packages.yml

- name: Ensure that Network Manager is started and enabled
  become: true
  ansible.builtin.systemd:
    state: started
    enabled: true
    name: NetworkManager

- name: Configure connections
  ansible.builtin.include_tasks:
    file: connections_setup.yml

- name: Ensure infra folder exists
  ansible.builtin.file:
    path: "{{ ansible_user_dir }}/.infra"
    state: directory

- name: Copy role related vars to the infra directory
  ansible.builtin.copy:
    content: >-
      {{
        {
          'pbi_network_connections': pbi_network_connections
        } | to_nice_yaml
      }}
    dest: "{{ ansible_user_dir }}/.infra/networking.yaml"
