---
## Reached this point ifup/idown managed interfaces exists -> Migrate to NM

- name: Make Network Manager manage external connections
  become: true
  community.general.ini_file:
    path: "{{ pbi_nstp_nm_config_path }}"
    section: ifupdown
    option: managed
    value: "true"
    mode: '0600'

# Ensures that dhclient is still used and DUID is preserved (same client-id == same IP)
- name: Use dhclient instead
  become: true
  community.general.ini_file:
    path: "/etc/NetworkManager/conf.d/dhcp-client.conf"
    section: main
    option: dhcp
    value: "dhclient"
    mode: '0600'

- name: Comment out all the interfaces declared in the interfaces file
  become: true
  pablintino.base_infra.delete_iface_from_net_interfaces:
    skip_interfaces:
      - lo
      - loopback
  register: pbi_nstp_nm_interfaces_file_removed

# Kill already existing dhclient processes to allow NM to take control of the iface
- name: Kill dhclient PIDs for each migrated interface
  vars:
    dhclient_regex: \\/?dhclient\\s(.)*\\s{{item}}$
  become: true
  ansible.builtin.command:
    cmd: "pgrep -f {{dhclient_regex}}"
  register: pbi_nstp_iface_dhclient_pids
  failed_when: >-
    pbi_nstp_iface_dhclient_pids.rc != 0 and
    pbi_nstp_iface_dhclient_pids.rc != 1 and
    pbi_nstp_iface_dhclient_pids.stderr != ''
  loop: "{{ pbi_nstp_nm_interfaces_file_removed.removed_ifaces.keys()|list }}"

- name: Restart networking
  become: true
  ansible.builtin.systemd:
    state: restarted
    enabled: true
    name: networking

- name: Restart the Network Manager to apply changes
  become: true
  ansible.builtin.systemd:
    state: restarted
    enabled: true
    name: NetworkManager

- name: Fetch connections to remove the autogenerated ones that are not active
  pablintino.base_infra.nmcli_get_connections:
  register: pbi_nstp_nm_connections_after_migration

- name: Remove unused autogenerated connections before making any change to the active one
  become: true
  ansible.builtin.command:
    cmd: "nmcli connection delete {{ item.value.connection_uuid }}"
  loop: >-
    {{
      pbi_nstp_nm_connections_after_migration.result |
      pablintino.base_infra.nmcli_connections_filter(active=false, ifaces=pbi_nstp_nm_interfaces_file_removed.removed_ifaces)
      | dict2items
    }}
  loop_control:
    label: "{{ item.key }}"

- name: Ensure connections are configured to autoconnect and activate them
  become: true
  ansible.builtin.shell:
    # Perform this in a single shell call cause the modify will cause interruption of the connection that won't be
    # recovered if connection activation is not properly done
    cmd: >-
      nmcli connection modify {{ item.value.connection_uuid }} connection.autoconnect yes &&
      nmcli connection up {{ item.value.connection_uuid }}
  loop: >-
    {{
      pbi_nstp_nm_connections_after_migration.result |
      pablintino.base_infra.nmcli_connections_filter(active=true, ifaces=pbi_nstp_nm_interfaces_file_removed.removed_ifaces)
      | dict2items
    }}
  loop_control:
    label: "{{ item.key }}"
