---
- name: Apply the connections configuration
  become: true
  pbtn.common.nmcli_apply:
    connections: "{{ pbi_nstp_connections }}"

- name: Refresh network related facts for further usage
  ansible.builtin.setup:
    gather_subset:
      - all_ipv4_addresses
      - all_ipv6_addresses
      - network
      - default_ipv4
      - default_ipv6

- name: Create the main networking fact of the role
  ansible.builtin.set_fact:
    pbi_network_connections: "{{ pbi_nstp_connections | default({}) }}"
    cacheable: true
