---
- name: Ensure that Network Manager is started and enabled
  become: true
  ansible.builtin.systemd:
    state: started
    enabled: true
    name: NetworkManager

- name: Flag interfaces file migration if needed
  ansible.builtin.import_tasks:
    file: migration_interfaces_file_check.yml

- name: Flag netplan interfaces migration if needed
  ansible.builtin.import_tasks:
    file: migration_netplan_check.yml

- name: Migrate interfaces from ifaces file to NM
  when: pbi_nstp_migrate_from_netplan_need | bool
  ansible.builtin.include_tasks:
    file: migration_netplan_to_nm_tasks.yml

- name: Migrate interfaces from ifaces file to NM
  when: pbi_nstp_migrate_from_interfaces_file_need | bool
  ansible.builtin.include_tasks:
    file: migration_interfaces_file_to_nm_tasks.yml
