---
- name: Ensure that Network Manager is started and enabled
  become: true
  ansible.builtin.systemd:
    state: started
    enabled: true
    name: NetworkManager

- name: Flag interfaces file migration if needed
  ansible.builtin.import_tasks:
    file: migration_interfaces_file_check.yml

- name: Flag netplan interfaces migration if needed
  ansible.builtin.import_tasks:
    file: migration_netplan_check.yml

- name: Migrate interfaces from ifaces file to NM
  when: pbi_nstp_migrate_from_netplan_need | bool
  ansible.builtin.include_tasks:
    file: migration_netplan_to_nm_tasks.yml

- name: Migrate interfaces from ifaces file to NM
  when: pbi_nstp_migrate_from_interfaces_file_need | bool
  ansible.builtin.include_tasks:
    file: migration_interfaces_file_to_nm_tasks.yml

- name: Gather the updated services list
  ansible.builtin.service_facts:

# Ensure networkd wait-online is disabled as it may interfere with NM
- name: Disable networkd wait-online (boot)
  vars:
    _wait_online_service: "systemd-networkd-wait-online.service"
  when:
    - "_wait_online_service in ansible_facts.services"
    - "ansible_facts.services[_wait_online_service].source == 'systemd'"
  become: true
  ansible.builtin.systemd:
    name: "{{ _wait_online_service }}"
    enabled: no
    state: stopped
