---
# Should be done before package installation
- name: Ensure dnf pre-requirements
  become: true
  vars:
    _pbi_pknst_dnf_prereqs_tuple: >-
      {{
        pbi_pknst_repos_install_list |
        default([]) |
        subelements('dnf_dependencies', {'skip_missing': True})
      }}
  when:
    - ansible_pkg_mgr == "dnf"
    - _pbi_pknst_dnf_prereqs_tuple | length > 0
  block:
    - name: Install dnf config-manager plugin before using it
      ansible.builtin.dnf:
        name: "dnf-plugins-core"
        state: present

    - name: Fetch the installed repositories list
      register: _pbi_pknst_dnf_repo_list_out
      ansible.builtin.command:
        cmd: "dnf repolist"
      changed_when: false

    - name: Enable needed dnf repos
      vars:
        _pbi_pknst_dnf_installed_repos: >-
          {{
            _pbi_pknst_dnf_repo_list_out.stdout_lines[1:] |
            map('split', ' ') |
            map('first')
          }}
      when: item.1 not in _pbi_pknst_dnf_installed_repos
      ansible.builtin.command:
        cmd: "dnf config-manager --set-enabled {{ item.1 }}"
      loop: "{{ _pbi_pknst_dnf_prereqs_tuple }}"

- name: Add apt repositories
  become: true
  ansible.builtin.apt_repository:
    repo: "{{ item.repo }}"
    filename: "{{ item.file | default(omit) }}"
    state: present
  with_items: "{{ pbi_pknst_repos_install_list }}"
  when: ansible_pkg_mgr == "apt"

- name: Add rpm repositories
  become: true
  ansible.builtin.yum_repository:
    name: "{{ item.name }}"
    baseurl: "{{ item.url }}"
    description: "{{ item.description }}"
    file: "{{ item.file | default(omit) }}"
  # Filter out packages that doesn't contain URL (packages installed by using dnf_dependencies)
  loop: "{{ pbi_pknst_repos_install_list | selectattr('url', 'defined') }}"
  when: ansible_pkg_mgr == "yum" or ansible_pkg_mgr == "dnf"
