---
- name: Set packages and repositories to be installed
  ansible.builtin.set_fact:
    package_install_effective_packages: "{{ package_install_base_packages | default([]) + package_install_packages | default([]) }}"
    package_install_effective_repositories: "{{ package_install_base_repositories | default([]) + package_install_repositories | default([]) }}"

- name: Print repositories and packages to be installed
  vars:
    to_install:
      packages: "{{ package_install_effective_packages }}"
      repositories: "{{ package_install_effective_repositories }}"
  ansible.builtin.debug:
    var: to_install

- name: Install given repositories
  vars:
    package_install_repos_list: "{{ package_install_effective_repositories }}"
  ansible.builtin.import_tasks:
    file: install_repos.yml

- name: Install given packages
  vars:
    package_install_packages_list: "{{ package_install_effective_packages }}"
  ansible.builtin.import_tasks:
    file: cache_update_install_packages.yml
