---
- name: Set packages and repositories to be installed
  ansible.builtin.set_fact:
    _pbi_pknst_effective_packages: "{{ pbi_pknst_base_packages | default([]) + pbi_pknst_packages | default([]) }}"
    _pbi_pknst_effective_repositories: "{{ pbi_pknst_base_repositories | default([]) + pbi_pknst_repositories | default([]) }}"
    cacheable: true

- name: Print repositories and packages to be installed
  vars:
    _pbi_pknst_to_install_data:
      packages: "{{ _pbi_pknst_effective_packages }}"
      repositories: "{{ _pbi_pknst_effective_repositories }}"
  ansible.builtin.debug:
    var: _pbi_pknst_to_install_data

- name: Install given repositories
  vars:
    pbi_pknst_repos_install_list: "{{ _pbi_pknst_effective_repositories }}"
  ansible.builtin.import_tasks:
    file: install_repos.yml

- name: Install given packages
  vars:
    pbi_pknst_packages_install_list: "{{ _pbi_pknst_effective_packages }}"
  ansible.builtin.import_tasks:
    file: install_packages.yml
