---
dependency:
  name: galaxy
driver:
  name: podman
platforms:
  - name: rocky-9
    image: rockylinux:9
    pre_build_image: true

  - name: debian-11
    image: debian:bullseye
    pre_build_image: false

  - name: ubuntu-22
    image: ubuntu:22.04
    pre_build_image: false

provisioner:
  name: ansible
verifier:
  name: ansible
scenario:
  name: default
  test_sequence:
    - destroy
    - create
    - prepare
    - converge
    - idempotence
    - verify
    - destroy
