---
- name: Converge
  hosts: all
  gather_facts: true
  tasks:
    - name: Calculate the attached private network interfaces macaddress and interface name
      vars:
        mngt_ip_addr: "{{ ansible_default_ipv4.address|default(ansible_all_ipv4_addresses[0]) }}"
        ssh_connection_iface: >-
            {{
                (
                  hostvars[inventory_hostname].values() |
                  selectattr('macaddress', 'defined') |
                  selectattr('device', 'defined') |
                  selectattr('ipv4.address', 'defined') |
                  selectattr('ipv4.address', 'equalto', mngt_ip_addr) |
                  first
                ).device
            }}
        custom_net_ifaces_facts: >-
          {{
            hostvars[inventory_hostname].values() |
            selectattr('macaddress', 'defined') |
            selectattr('device', 'defined') |
            rejectattr('device', 'equalto', ssh_connection_iface) |
            rejectattr('device', 'equalto', "lo")
          }}
      ansible.builtin.set_fact:
        pbi_tst_nstp_custom_net_ifaces_facts: "{{ custom_net_ifaces_facts }}"

    - name: Save the interfaces names for further verification
      vars:
        pbi_test_ifaces:
          internal1: "{{ pbi_tst_nstp_custom_net_ifaces_facts[0].device }}"
          mngt: "{{ pbi_tst_nstp_custom_net_ifaces_facts[1].device }}"
      ansible.builtin.copy:
        content: "{{ pbi_test_ifaces | to_nice_yaml }}"
        dest: "/tmp/test-ifaces.yaml"

    - name: "Include role under test"
      vars:
        pbi_nstp_connections:
          internal1:
            device-type: ethernet
            mac: "{{ pbi_tst_nstp_custom_net_ifaces_facts[0].macaddress }}"
            mode: auto
          mngt:
            device-type: ethernet
            iface: "{{ pbi_tst_nstp_custom_net_ifaces_facts[1].device }}"
            mode: auto
      ansible.builtin.include_role:
        name: "pablintino.base_infra.networking_setup"
