---
- name: Prepare
  hosts: all
  gather_facts: true
  tasks:
    - name: Save the interfaces names for further verification
      vars:
        # Do not trust ansible_facts to determine the ssh config as
        # it varies in consecutive runs as interfaces/conns are added
        mngt_ip_addr: "{{ (ansible_env.SSH_CONNECTION | split(' '))[2]}}"
        ssh_connection_iface: >-
          {{
              (
                hostvars[inventory_hostname].values() |
                selectattr('macaddress', 'defined') |
                selectattr('device', 'defined') |
                selectattr('ipv4.address', 'defined') |
                selectattr('ipv4.address', 'equalto', mngt_ip_addr) |
                first
              ).device
          }}
        custom_net_ifaces_facts: >-
          {{
            hostvars[inventory_hostname].values() |
            selectattr('macaddress', 'defined') |
            selectattr('device', 'defined') |
            rejectattr('device', 'equalto', ssh_connection_iface) |
            rejectattr('device', 'equalto', "lo")
          }}
        module_connections_config:
          molecule:
            type: ethernet
            iface: "{{ ssh_connection_iface }}"
            state: up
            ipv4:
              mode: auto
          internal:
            type: bridge
            iface: br123
            state: up
            ipv6:
              # Vagrant infra doesn't support DHCP. Testing IPv6 statically
              mode: manual
              ip: fd68:4327:d6f9:2240::ab/64
              dns:
                - fd68:4327:d6f9:2240::01
                - fd68:4327:d6f9:2240::02
            slaves:
              internal-1:
                type: ethernet
                iface: "{{ custom_net_ifaces_facts[0].macaddress }}"
              internal-2:
                type: ethernet
                iface: "{{ custom_net_ifaces_facts[1].device }}"
        content:
          pbi_tst_nstp_ifaces:
            internal: "{{ module_connections_config.internal.iface }}"
            internal-1: "{{ custom_net_ifaces_facts[0].device }}"
            internal-2: "{{ custom_net_ifaces_facts[1].device }}"
            molecule: "{{  ssh_connection_iface }}"
          pbi_tst_nstp_connections_config: "{{ module_connections_config }}"
          pbi_tst_nstp_ssh_interface: "{{ ssh_connection_iface }}"
      ansible.builtin.copy:
        content: "{{ content | to_nice_yaml }}"
        dest: "/tmp/test-ifaces.yaml"

    # Observed that some VMs may contain inactive connections for
    # devices that are not even present. Try to start from a clean
    # NM state if NM is present
    - name: Check is nm is installed
      shell: command -v nmcli >/dev/null 2>&1
      register: pbi_tst_nstp_prep_nm_exits
      failed_when: false

    - name: Perform NM cleanup
      when: "pbi_tst_nstp_prep_nm_exits.rc == 0"
      block:
        - name: Fetch connections statuses
          ansible.builtin.command:
            cmd: "nmcli -t -f UUID,STATE conn show"
          register: pbi_tst_nstp_connections_statuses

        - name: Clean inactive connections
          vars:
            to_delete_uuids: >-
              {{
                pbi_tst_nstp_connections_statuses.stdout_lines |
                reject("search", "activ") |
                map("split", ":") |
                map("first")
              }}
          become: true
          ansible.builtin.command:
            cmd: "nmcli conn delete {{ item }}"
          loop: "{{ to_delete_uuids }}"
