---
pbi_nstp_networking_output_file_path: "{{ ansible_user_dir }}/.infra/networking.yaml"
pbi_nstp_nm_config_path: "/etc/NetworkManager/NetworkManager.conf"
pbi_nstp_netplan_config_dir: "/etc/netplan/"
pbi_nstp_netplan_disabling_config: |-
  # Ansible pablintino.base_infra managed
  network:
    renderer: NetworkManager
    version: 2
pbi_nstp_interfaces_file_ignored_ifaces:
  - loopback
  - lo
