---
pbi_nstp_wait_for_ip_delay: 20
pbi_nstp_wait_for_ip_retries: 20
pbi_nstp_nm_config_path: "/etc/NetworkManager/NetworkManager.conf"
pbi_nstp_netplan_config_dir: "/etc/netplan/"
pbi_nstp_netplan_disabling_config: |-
  # Ansible pablintino.base_infra managed
  network:
    renderer: NetworkManager
    version: 2
pbi_nstp_interfaces_file_ignored_ifaces:
  - loopback
  - lo
