---
- name: Set default rules initial lists
  ansible.builtin.set_fact:
    pbi_fwstp_default_input_list: "{{ pbi_fwstp_default_input_rules }}"
    pbi_fwstp_default_output_list: "{{ pbi_fwstp_default_output_rules }}"
    cacheable: true

- name: Append SSH input rule for the managment interface
  vars:
    managment_conn_ipv4: >-
      {{
        (
          pbi_networking_mngt_connection_config.ipv4.ip |
          default('') |
          split('/') |
          first
        )
        if ('ipv4' in pbi_networking_mngt_connection_config | default({}))
        else {}
      }}
  when: "pbi_networking_mngt_interface is defined"
  ansible.builtin.set_fact:
    pbi_fwstp_default_input_list: "{{ pbi_fwstp_default_input_list + [pbi_fwstp_default_rule_input_ssh_accept_template] }}"
    cacheable: true
