---
- name: Gather roles variables per SO
  ansible.builtin.include_vars:
    file: "{{ role_path }}/vars/{{ ansible_os_family | lower }}_vars.yml"

- name: Remove the native firewall
  become: true
  ansible.builtin.package:
    name: "{{ pbi_fwstp_native_firewall_service_name }}"
    state: absent

- name: Install firewall related packages
  vars:
    pbi_pknst_packages_install_list: "{{ pbi_fwstp_packages }}"
    pbi_pknst_install_exec_condition: nft
  ansible.builtin.include_role:
    name: package_install
    tasks_from: install_packages.yml

# nftables is a single shot service that pushes rules to the kernel so
# there is no need to start it. Enabling it allow pushing the rules on boot
- name: Enable the nftables service
  become: true
  ansible.builtin.systemd:
    name: nftables
    enabled: true

- name: Try loading the networking metadata
  ansible.builtin.include_role:
    name: networking_setup
    tasks_from: load_networking_vars.yml

- name: Compute default rules lists
  ansible.builtin.include_tasks:
    file: build_default_rules_list.yml

- name: Apply rules if necessary
  become: true
  pablintino.base_infra.nftables_apply:
    target_config_file: "{{ pbi_fwstp_nftables_file }}"
    config: "{{ lookup('ansible.builtin.template', pbi_fwstp_rules_template) }}"
