---
- name: Install firewalld and related tools
  vars:
    package_install_packages_list:
      - python3-firewall
      - firewalld
  ansible.builtin.import_role:
    name: package_install
    tasks_from: cache_update_install_packages.yml


