---
dependency:
  name: galaxy

driver:
  name: vagrant
  provider:
    name: libvirt
    type: libvirt

provisioner:
  name: ansible
  connection_options:
    ansible_ssh_user: vagrant
    ansible_become: true

platforms:
  - name: ubuntu-22
    box: generic/ubuntu2204
    memory: 1024
    cpus: 2
    config_options:
      ssh.keep_alive: yes
      ssh.remote_user: "vagrant"
    interfaces:
      - auto_config: true
        network_name: private_network
        type: static
        ip: 192.168.10.10

  - name: debian-11
    box: debian/bullseye64
    memory: 1024
    cpus: 2
    config_options:
      ssh.keep_alive: yes
      ssh.remote_user: "vagrant"
    interfaces:
      - auto_config: true
        network_name: private_network
        type: static
        ip: 192.168.10.12

  - name: rocky-9
    box: rockylinux/9
    memory: 1024
    cpus: 2
    config_options:
      ssh.keep_alive: yes
      ssh.remote_user: "vagrant"
    interfaces:
      - auto_config: true
        network_name: private_network
        type: static
        ip: 192.168.10.11

verifier:
  name: ansible

scenario:
  name: default
  test_sequence:
    - destroy
    - create
    - prepare
    - converge
    - idempotence
    - verify
    - destroy
