---
dependency:
  name: galaxy

driver:
  name: vagrant
  provider:
    name: libvirt
    type: libvirt

provisioner:
  name: ansible
  connection_options:
    ansible_ssh_user: vagrant
    ansible_become: true
  config_options:
    ssh_connection:
      pipelining: true

platforms:
  - name: ubuntu-22
    box: generic/ubuntu2204
    memory: 1024
    cpus: 2
    config_options:
      ssh.keep_alive: yes
      ssh.remote_user: "vagrant"
    interfaces:
      - network_name: private_network
        type: dhcp
        auto_config: false

      - network_name: private_network
        type: static
        mac: d2:55:ee:86:11:24
        auto_config: false
        ip: 172.17.199.2

  - name: debian-11
    box: debian/bullseye64
    memory: 1024
    cpus: 2
    config_options:
      ssh.keep_alive: yes
      ssh.remote_user: "vagrant"
    interfaces:
      - network_name: private_network
        type: dhcp
        auto_config: false

      - network_name: private_network
        type: static
        mac: d2:55:ee:86:11:25
        auto_config: false
        ip: 172.17.199.3

  - name: rocky-9
    box: rockylinux/9
    memory: 1024
    cpus: 2
    config_options:
      ssh.keep_alive: yes
      ssh.remote_user: "vagrant"
    interfaces:
      - network_name: private_network
        type: dhcp
        auto_config: false

      - network_name: private_network
        type: static
        mac: d2:55:ee:86:11:26
        auto_config: false
        ip: 172.17.199.4

verifier:
  name: ansible

scenario:
  name: default
  test_sequence:
    - destroy
    - create
    - prepare
    - converge
    - idempotence
    - verify
    - destroy
